#Controls whether player-wielded non-melee weapons and offensive machines FROM THIS MOD ONLY can damage other players.
#This setting respects the base game's PVP rule. Use this if you want PVP but otherwise feel that this mod's weaponry is too unbalanced.
enable_mod_pvp = false
#Base energy capacity of the ε-Series tools
# Default: 80000
# Range: > 1
tools_energy_capacity = 80000
#Base energy cost per action (dig/attack/etc.) of the ε-Series tools
# Default: 400
# Range: > 1
tools_energy_per_action = 400
#Base energy capacity of the WNDR-L armor pieces
# Default: 125000
# Range: > 1
armor_energy_capacity = 125000
#Base energy post per action (reduce damage/stop falls/etc.) of the WNDR-L armor pieces
# Default: 500
# Range: > 1
armor_energy_per_action = 500
#How much shield health it costs to block a mob effect. Affects both entity and player shields
# Default: 2.0
# Range: 0.0 ~ 1000.0
shield_effect_block_cost = 2.0
